name: Build & Push to Docker Hub

on:
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout implement/Api
      uses: actions/checkout@v3
      
    - name: List files for debugging
      run: ls -R

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/webapplication1:latest -f WebApplication1/Dockerfile .


    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ steps.lower.outputs.image_name }}:latest
